apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metric.name" . }}
  labels:
    {{- include "metric.labels" . | nindent 4 }}
data:
  metric.toml: |
    {{- include "metric.config" . | nindent 4 }}
