{{- if and (eq .Values.blob.backend "local") (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "metric.blobClaim" . }}
  labels:
    {{- include "metric.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    helm.sh/resource-policy: keep
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- if kindIs "string" .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ include "metric.blobSize" . | quote }}
{{- end }}
